#logging.level.org.springframework.web.client.RestTemplate=DEBUG
#logging.level.org.apache.http=DEBUG
#logging.level.httpclient.wire=DEBUG
server.port=8080
client.url=http://localhost:9090
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:main;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_UPPER=FALSE;
spring.datasource.username=main
spring.datasource.password=main